#! /usr/bin/env bash

if [ $# != 1 ]; then
    echo "usage: $0 <install-prefix>"
    exit 1
fi

OS="$(uname)"

if [ "$OS" == "Darwin" ]; then
  sysroot="-isysroot $(xcodebuild -version -sdk macosx Path)"
fi

$1/bin/clang++ $sysroot --std=c++17 --stdlib=libc++ test.cc -o a.out -lc++experimental  && ./a.out
#rm -f a.out
